### ISSUE TITLE
HTML file not included

### ISSUE THREAD

**Issue by pawamoy** [laffra/pynsights#1]
I installed your project with `pip install git+https://github.com/laffra/pynsights`, added the import statement, and then tried to run it. But the HTML file was missing. I guess your setup.py lacks one or two configuration options :slightly_smiling_face:

**Comment by laffra** [comment]
I will take a look.

**Comment by laffra** [comment]
I updated setup.py and added a MANIFEST.in to ensure the html file is copied when using `pip install git+`. If you run the command once more, it should work better now.

**Comment by pawamoy** [comment]
Thanks!
