### ISSUE TITLE
Three.js Javascript error on all HTML output

### ISSUE THREAD

**Issue by GeospatialPython** [laffra/pynsights#12]
All HTML examples and custom output do not run due to a javascript error:

`Uncaught TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../".`

It appears to be a change in the latest version of three.js pulled through the unpkg cdn:

[https://github.com/mrdoob/three.js/issues/22008](https://github.com/mrdoob/three.js/issues/22008)

I haven't been able to manually fix it yet in example.html without causing additional errors.

**Comment by laffra** [comment]
Forcing three to version 0.126.1 solved this issue.

**Comment by laffra** [comment]
Please try again with the latest.

**Comment by GeospatialPython** [comment]
Works great! Thank you!
