### ISSUE TITLE
Loading... nothing happens

### ISSUE THREAD

**Issue by pawamoy** [laffra/pynsights#2]
After manually copying (#1) the HTML file into my packages installation directory, I ran my code again. This time the HTML file is found by my browser but... nothing happens. It just says Loading... at the top, and shows the regex filter and some checkboxes. Any idea? Am I doing something wrong?

**Comment by laffra** [comment]
Let me try to set up the project the same way you did with "pip install". I
never tried that.

**Comment by laffra** [comment]
The browser console for the HTML file may give some information?

**Comment by laffra** [comment]
The logic for handling bootstrap call was overly expensive (involving stack analysis). I replaced it with an exception handling and pynsights runs much faster now. Can you update to the latest and try again?

**Comment by laffra** [comment]
Any luck with this? Just want to make sure I need to fix anything....

**Comment by pawamoy** [comment]
Sorry, didn't have the time to try it yet, but will for sure 🙂 
Thank you!

**Comment by laffra** [comment]
Would love to see some screenshots/gifs if you get it working. Thanks for trying and going through the first setup problems...

**Comment by pawamoy** [comment]
OK, it works! It seems to start faster if I delay the import of pynsights in my code, to avoid tracing imports of many modules.

**Comment by pawamoy** [comment]
![pynsights-griffe](https://user-images.githubusercontent.com/3999221/140546501-4168f8d5-4b69-46df-911c-a82710183f03.gif)

**Comment by pawamoy** [comment]
Sorry about the quality. I used peek to capture the screen as GIF, which is one the best tools I found to do this, but the image still jumps from time to time. I also had to compress the GIF so some quality was lost in the process :sweat_smile:

**Comment by pawamoy** [comment]
Anyway, your tool is fantastic @laffra! I really enjoy it, and have many feature requests coming :smiling_imp: 
Closing as this issue is resolved :smile:
