### ISSUE TITLE
Add a CLI with record and view/render commands

### ISSUE THREAD

**Issue by pawamoy** [laffra/pynsights#6]
I'm willing to implement this, but lets discuss it first to make sure we're on the same page.

Currently, users have to modify their code to record data. What would be great is to be able to run `pynsights record <module> [options]` to record the data, then `pynsights view <datafile.txt>`. You could use it on installed modules without having to go hack their main entrypoint.

We could consider supporting options for these commands as well:

- `pynsights record -o output.pynsights module -- --module-option=value` (maybe the output option could be made a required, positional argument so we don't need `--`)
- `pynsights render output.pynsights --open` (do not open in browser by default)

Let me know what you think :slightly_smiling_face: 

I can take care of all the CLI machinery (entrypoint in setup.py, argument parser with argparse, etc.)

**Comment by laffra** [comment]
Great idea. Would love to see you implement it.

**Comment by pawamoy** [comment]
Awesome! I'll send a PR very soon :slightly_smiling_face:
